# Copyright.adoc
:Title: SISO Copyright
:titletext: Draft SISO Copyright
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 3
:numbered:
:sectanchors:
:source-highlighter: coderay

= {title}

Copyright © 2020 by the Simulation Interoperability Standards Organization, Inc.

P.O. Box 781238

Orlando, FL 32878-1238, USA

All rights reserved.



Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and make derivative works from this material, for all purposes, provided that any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” Should a reader require additional information, contact the SISO Inc. Board of Directors.



Documentation: SISO hereby grants a general, royalty-free license to copy, distribute, display, and make derivative works from this material, for noncommercial purposes, provided that any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” The material may not be used for a commercial purpose without express written permission from the SISO Inc. Board of Directors.



SISO Inc. Board of Directors

P.O. Box 781238

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) 2021 Simulation Interoperability Standards Organization, Inc.
|To obtain additional rights of use, visit URI resource in our new IT infrastructure
|===
