
:Title: SISO Copyright
//:titletext: Draft SISO Copyright
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 3
:numbered:
:sectanchors:
:source-highlighter: coderay

= {title}

Copyright © 2021 by the Simulation Interoperability Standards Organization, Inc.

7901 4th St N.
Suite 300
St. Petersburg, FL  33702

All rights reserved, worldwide.


//Changed SISO to SISO, Inc. everywhere in this document because 'SISO' isn't a legal entity and can't grant anything
Schemas and APIs, including Documentation: SISO Inc. hereby grants a general, royalty-free license to copy, distribute, display, and make derivative works from this material, for all purposes, provided that any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” Should a reader require additional information, contact the SISO Inc. Board of Directors.



Documentation: SISO Inc. hereby grants a general, royalty-free license to copy, distribute, display, and make derivative works from this material, for noncommercial purposes, provided that any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” The material may not be used for a commercial purpose without express written permission from the SISO Inc. Board of Directors.



SISO Inc. Board of Directors

7901 4th St N.
Suite 300
St. Petersburg, FL  33702

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) 2021 Simulation Interoperability Standards Organization, Inc.
|To obtain additional rights of use, visit URI resource in our new IT infrastructure
|===
